### ISSUE TITLE
用最新版提示这个报错

### ISSUE THREAD

**Issue by Baikele** [saltedfishclub/MiraiAdapter#5]
[10:07:20 ERROR]: Could not load 'plugins\MiraiAdapter-2.0-all.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: cc/sfclub/mirai/AdapterMain has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:318) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:222) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_321]
Caused by: java.lang.UnsupportedClassVersionError: cc/sfclub/mirai/AdapterMain has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_321]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_321]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_321]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_321]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_321]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_321]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_321]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.12.2.jar:git-Paper-1618]
        ... 6 more

**Comment by iceBear67** [comment]
虽然你大概率已经不需要了，  
但你要找的是 [Minecraft2Mirai](https://github.com/iceBear67/Minecraft2Mirai) 而不是这个。  
这是我机器人框架的插件。
